sudo: false
language: node_js
node_js:
  - 6
notifications:
  email: false
script: npm run build
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: ./dist/Whale-osx-${npm_package_version}.zip
  skip_cleanup: true
  on:
    tags: true
